# Generated by Django 3.2.16 on 2022-12-12 13:41

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('medication', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='records',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('upload', models.FileField(upload_to=app.models.user_directory_path)),
                ('time_limit', models.DateTimeField()),
                ('approval_doc', models.CharField(default='B', max_length=1)),
                ('approval_rec', models.CharField(default='B', max_length=1)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
    ]
