# Generated by Django 3.2.16 on 2022-12-12 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_records_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='records',
            old_name='upload',
            new_name='document',
        ),
    ]
